Anonymous functions
carbon-app/carbon pull request #1111
Opened 2020-10-02 09:47 UTC by Aslemammad

#1090

2020-10-03 17:10 UTC, Aslemammad commented
@kavu

2020-10-03 17:40 UTC, mfix22 requested changes
@Aslemammad Thanks so much! Just have some style adjustments I'd like to make, but besides that this is great

2020-10-03 17:40 UTC, mfix22 commented on components/Billing.js
> +const ExportedBilling = () => {
Please use: 
```suggestion
export default function ExportedBilling() {
```

2020-10-03 17:40 UTC, mfix22 commented on components/style/Font.js
> +const Font = () => (
```suggestion
export default function Font() {
```

2020-10-03 17:40 UTC, mfix22 commented on components/style/Reset.js
> +const Reset = () => (
```suggestion
export default function Reset() {
```

2020-10-03 17:40 UTC, mfix22 commented on components/style/Typography.js
> +const Typography = () => (
```suggestion
export default function Typography() {
```

2020-10-03 17:40 UTC, mfix22 commented on components/svg/Language.js
> +const Language = () => (
```suggestion
export default function Language() {
```

2020-10-03 17:40 UTC, mfix22 commented on components/svg/Logo.js
> +const Logo = () => (
```suggestion
export default function Logo() {
```

2020-10-03 17:40 UTC, mfix22 commented on components/svg/Settings.js
> +const Settings = () => (
```suggestion
export default function Settings() {
```

2020-10-03 17:40 UTC, mfix22 commented on components/svg/Theme.js
> +const Theme = () => (
```suggestion
export default function Theme() {
```

2020-10-03 17:40 UTC, mfix22 commented on pages/about.js
> +const About = () => (
```suggestion
export default function About() {
```

2020-10-03 17:40 UTC, mfix22 commented on pages/snippets.js
> +const Snippets = () => (
```suggestion
export default function Snippets() {
```

2020-10-03 17:40 UTC, mfix22 commented on pages/snippets.js
> +  const config = {
Please keep this as is, unless prettier adjusted this for you.

2020-10-03 17:40 UTC, mfix22 commented on components/Billing.js
> +      <style jsx>
Please keep this as is, unless Prettier adjusted this for you

2020-10-03 19:47 UTC, Aslemammad commented
@mfix22 I made the new changes. Thanks.

2020-10-03 19:54 UTC, mfix22 requested changes
@Aslemammad a couple more changes! 

Other open issues: 
* https://github.com/carbon-app/carbon/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest
* https://github.com/carbon-app/carbon/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+

2020-10-03 19:54 UTC, mfix22 commented on components/Billing.js
> +export default function ExportedBilling() {
```suggestion
export default function BillingPage() {
```

2020-10-03 19:54 UTC, mfix22 commented on pages/snippets.js
> +  const config = {
Is this from Prettier? Or can you keep this as is?

2020-10-03 20:49 UTC, Aslemammad commented
No, it's from prettier config.

2020-10-04 22:45 UTC, merged

2020-10-05 04:59 UTC, Aslemammad commented
Thanks for merge.